apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  # namespace: web-development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: hhylalala/go-backend:1.0
        ports:
        - containerPort: 8080
