apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  # namespace: web-development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: hhylalala/reactjs-frontend:1.0
        ports:
        - containerPort: 3000
