apiVersion: v1
kind: Service
metadata:
  name: react-service
  # namespace: web-development
spec:
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
