apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: hhylalala/reactjs-frontend:1.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: default
spec:
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: hhylalala/go-backend:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: default
spec:
  selector:
    app: go
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

